### ISSUE TITLE
Kbin offline

### ISSUE THREAD

**Issue by TwentySeven28** [garrettw/kbin-core#1]
I've been receiving the following error message for more than eight hours:

> We are working on resolving the issues
> Over the next few days, there will be a change in server infrastructure. Temporary problems with the website's functionality may occur during this time.

**Comment by garrettw** [comment]
This repo is just a copy of the official one, and I'm not an official kbin developer. I can't do anything about this.

The official issue tracker can be found at: https://codeberg.org/Kbin/kbin-core/issues
